# Generated by Django 4.0.5 on 2022-06-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='color',
            field=models.CharField(default=1, max_length=50, verbose_name='color'),
            preserve_default=False,
        ),
    ]
