# Generated by Django 4.0.5 on 2022-06-05 21:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skills_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=100, verbose_name='Who')),
                ('about', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
