# Generated by Django 4.0.5 on 2022-06-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_certificate_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=150, verbose_name='School')),
                ('date', models.TextField(max_length=10, verbose_name='Date')),
                ('branch', models.CharField(blank=True, max_length=50, null=True, verbose_name='Branch')),
            ],
        ),
    ]
