# Generated by Django 4.0.5 on 2022-06-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.CharField(max_length=50, verbose_name='Date'),
        ),
    ]
